name: Create Release AnyText Executable

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build the executable with PyInstaller
        run: pyinstaller scripts/AnyText.spec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/AnyText.exe
          fail_on_unmatched_files: true
          body: "Automated release of the AnyText application."
